config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :trips do
    resources :products
    member do
      get 'select_application'
      post 'update_application'
      post 'commit_application'
    end
  end

  resources :products do
    resources :purchasings
  end

  get 'welcome/index'

  devise_for :users
  namespace :api do
    post 'users/sign_in' => 'sessions#create'
    post 'users/sign_up' => 'registrations#create'
  end

  root 'welcome#index'

  get '/edit_avatar' => 'user_manage#edit_avatar'
  patch '/update_avatar' => 'user_manage#update_avatar'

  get "/:member_id" => "user_manage#show", :as => "member"

end

app/models/purchasing.rb
class Purchasing
  include Mongoid::Document
  include Mongoid::Timestamps

  field :expect_time_start, type: Date #期望到货时间
  field :expect_time_end, type: Date #期望到货时间
  field :remuneration, type: BigDecimal #酬金
  field :memo, type: String #备注
  field :quantity, type: BigDecimal #数量
  field :status, type: String, default: 'applying'

  belongs_to :user
  belongs_to :trip
  belongs_to :product

  validates_presence_of :expect_time_start, :expect_time_end, :remuneration, :memo, :quantity
  

  before_create do
    #创建商品同时,创建的需求
    self.user_id = self.product.user_id if self.product.purchasings.count == 0
    self.trip_id = self.product.trip_id
  end

  after_create do
    self.trip.update_attributes(pur_num: self.trip.pur_num+1)
    self.product.update_attributes(pur_num: self.product.pur_num+1)
  end
end

app/controllers/purchasings_controller.rb
class PurchasingsController < ApplicationController
  before_action :set_purchasing, only: [:show, :edit, :update, :destroy]
  before_action :set_product
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  respond_to :html, :json

  def index
    @purchasings = Purchasing.all
    respond_with(@purchasings)
  end

  def show
    respond_with([@product, @purchasing])
  end

  def new
    @purchasing = Purchasing.new
    respond_with([@product, @purchasing])
  end

  def edit
  end

  def create
    @purchasing = Purchasing.new(purchasing_params)
    @purchasing.user = current_user
    @purchasing.product = @product
    @purchasing.save
    respond_with([@product, @purchasing])
  end

  def update
    @purchasing.update(purchasing_params)
    respond_with([@product, @purchasing])
  end

  def destroy
    @purchasing.destroy
    respond_with([@product, @purchasing])
  end

  private
    def set_purchasing
      @purchasing = Purchasing.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def purchasing_params
      params.require(:purchasing).permit(:expect_time_start, :expect_time_end, :remuneration, :memo, :quantity)
    end
end

app/helpers/purchasings_helper.rb
module PurchasingsHelper
end

app/views/purchasings/_form.html.erb
<%= form_for([@product, @purchasing]) do |f| %>
    <div class="row">
      <%= f.label :期望到货时间 %><br>
      <%= f.text_field :expect_time_start, class: "form-control" %>
    </div>
    <div class="row">
      <%= f.label :期望到货时间 %><br>
      <%= f.text_field :expect_time_end, class: "form-control" %>
    </div>
    <div class="row">
      <%= f.label :酬金 %><br>
      <%= f.text_field :remuneration, class: "form-control" %>
    </div>
    <div class="row">
      <%= f.label :备注 %><br>
      <%= f.text_field :memo, class: "form-control" %>
    </div>
    <div class="row">
      <%= f.label :数量 %><br>
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
    <div class="row"> 
      <%= f.submit '发布', class: "btn btn-block btn-primary" %>
    </div>
<% end %>

<script type="text/javascript">
  /* <![CDATA[ */
  jQuery(function(){
    jQuery("#purchasing_expect_time_start").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请填写类型"
    });
    jQuery("#purchasing_expect_time_end").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入名称"
    });
    jQuery("#purchasing_remuneration").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请填写描述"
    });
    jQuery("#purchasing_memo").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请填写日期"
    });
    jQuery("#purchasing_quantity").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请填写日期"
    });
  });
  /* ]]> */
</script>

app/views/purchasings/_purchasing.html.erb
<%= div_for purchasing do %>
<div class="sidebar-module sidebar-module-inset">
  <span class="fui-user">
  	<%=purchasing.user.name%>  
  	<% if purchasing.user == current_user && purchasing.status == "created" %>
      <%= link_to '删除', [purchasing.trip, purchasing], method: :delete, data: { confirm: 'Are you sure?' }, class: "like pull-right" %>
    <% elsif purchasing.status != "created" %>
      <%= {"selected"=>"已被选择", "unselected"=>"未被选择"}[purchasing.status]%>
    <% end %>
  </span>
  <p><%=purchasing.item_name%></p>
</div>
<% end %>

app/views/purchasings/edit.html.erb
<h1>Editing purchasing</h1>

<%= render 'form' %>

<%= link_to 'Show', trip_purchasing_path(@trip, @purchasing) %> |
<%= link_to 'Back', trip_purchasings_path %>

app/views/purchasings/index.html.erb
<h1>Listing purchasings</h1>

<table>
  <thead>
    <tr>
      <th>Item type</th>
      <th>Item name</th>
      <th>Item desc</th>
      <th>Url</th>
      <th>Arrival time start</th>
      <th>Arrival time end</th>
      <th>Item price desc</th>
      <th>Remuneration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchasings.each do |purchasing| %>
      <tr>
        <td><%= purchasing.item_type %></td>
        <td><%= purchasing.item_name %></td>
        <td><%= purchasing.item_desc %></td>
        <td><%= purchasing.url %></td>
        <td><%= purchasing.arrival_time_start %></td>
        <td><%= purchasing.arrival_time_end %></td>
        <td><%= purchasing.item_price_desc %></td>
        <td><%= purchasing.remuneration %></td>
        <td><%= link_to 'Show', trip_purchasing_path(@trip, purchasing) %></td>
        <td><%= link_to 'Edit', edit_trip_purchasing_path(@trip, purchasing) %></td>
        <td><%= link_to 'Destroy', [@trip,purchasing], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New purchasing', new_trip_purchasing_path %>

app/views/purchasings/new.html.erb
<h1>New purchasing</h1>

<%= render 'form' %>

app/views/purchasings/show.html.erb
<p>
  <strong>Remuneration:</strong>
  <%= @purchasing.remuneration %>
</p>