config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :trips do
    resources :products
    member do
      get 'select_application'
      post 'update_application'
      post 'commit_application'
    end
  end

  resources :products do
    resources :purchasings
  end

  get 'welcome/index'

  devise_for :users
  namespace :api do
    post 'users/sign_in' => 'sessions#create'
    post 'users/sign_up' => 'registrations#create'
  end

  root 'welcome#index'

  get '/edit_avatar' => 'user_manage#edit_avatar'
  patch '/update_avatar' => 'user_manage#update_avatar'

  get "/:member_id" => "user_manage#show", :as => "member"

end

app/models/trip.rb
class Trip
  include Mongoid::Document
  include Mongoid::Timestamps
  
  DEST_STATE = [['美国', 'us'], ['日本', 'jp'], ['韩国', 'kr'], ['德国', 'de'], ['澳大利亚', 'au'], ['其他', 'other']]
  field :trip_name, type: String #行程名称
  field :departure_date, type: Date #出发日期
  field :return_date, type: Date #返回日期
  field :expiration_date, type: Date #下单截止日期
  field :trip_desc, type: String #行程描述
  field :status, type: String, default: 'created'
  field :pur_num, type: BigDecimal, default: 0

  belongs_to :user
  embeds_many :pictures, :cascade_callbacks => true
  accepts_nested_attributes_for :pictures
  has_many :purchasings, :dependent => :destroy
  has_many :products, :dependent => :destroy
  has_many :comments, :as => :commentable, :dependent => :destroy

  validates_presence_of :trip_name, :departure_date, :return_date, :expiration_date, :trip_desc
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy, :select_application, :update_application, :commit_application]
  before_filter :authenticate_user_from_token!, only: [:new, :edit, :create, :update, :destroy, :select_application, :update_application, :commit_application]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :select_application, :update_application, :commit_application]


  respond_to :html, :json

  def index
    @trips = Trip.all
    respond_with(@trips)
  end

  def show
    @purchasing = Purchasing.new
    respond_with(@trip)
  end

  def new
    @trip = Trip.new
    3.times { @trip.pictures.build }
    respond_with(@trip)
  end

  def edit
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    @trip.save
    respond_with(@trip)
  end

  def update
    @trip.update(trip_params)
    respond_with(@trip)
  end

  def destroy
    @trip.destroy
    respond_with(@trip)
  end

  def select_application
  end

  def update_application
    if params[:checkbox].nil? || params[:checkbox].blank?
      flash[:alert] = "您必须至少选择一个代购请求"
      redirect_to "/trips/#{@trip.id}/select_application"
    else
      params[:checkbox].each {|p| Purchasing.find(p).update_attributes(status: "selected")}
      Purchasing.where(status: "created").each {|p| p.update_attributes(status: "unselected")}
      @trip.update_attributes(status: "selected")
      respond_with(@trip)
    end
  end

  def commit_application
    @trip.update_attributes(status: "committed")
    respond_with(@trip)
  end

  private
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:trip_name, :departure_date, :return_date, :expiration_date, :trip_desc, pictures_attributes: [:attachment])
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip, :html => { :multipart => true }) do |f| %>
<div class="row">
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :行程名称 %><br>
    <%= f.text_field :trip_name, class: "form-control" %>
  </div>
  <div class="row">
    <%= f.label :行程描述 %><br>
    <%= f.text_area :trip_desc, class: "form-control", placeholder: "例如：经过哪些城市等" %>
  </div>
  <div class="row">
    <%= f.label :出发日期 %><br>
    <%= f.text_field :departure_date, class: "form-control" %>
  </div>
  <div class="row">
    <%= f.label :返回日期 %><br>
    <%= f.text_field :return_date, class: "form-control" %>
  </div>
  <div class="row">
    <%= f.label :下单截止日期 %><br>
    <%= f.text_field :expiration_date, class: "form-control" %>
  </div>
  <%= f.fields_for :pictures do |image| %>
    <% if image.object.new_record? %>
      <div class="row">
        <%= image.label :图片 %><br>
        <%= image.file_field :attachment, class: "form-control" %>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <%= f.submit '发布', class: "btn btn-block btn-primary" %>
  </div>
</div>
<% end %>

<script type="text/javascript">
  /* <![CDATA[ */
  jQuery(function(){
    jQuery("#trip_trip_name").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请选择国家"
    });
    jQuery("#trip_trip_desc").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请填写回国日期"
    });
    jQuery("#trip_departure_date").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
    jQuery("#trip_return_date").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
    jQuery("#trip_expiration_date").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
    jQuery("#trip_pictures_attributes_0_attachment").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
  });
  /* ]]> */
</script>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h4>代购行程</h4>
<% if @trips.count > 0 %>

  <% i = 0 %>
  <% @trips.each do |trip| %>
  <% if i!=@trips.count && i%4 == 0 %>
      <div class="row demo-tiles">
    <% end %>
      <div class="col-xs-3">
        <div class="tile">
          <%= image_tag "icons/png/Map.png" %>
          <h4><%= "#{dest_state_desc(trip.dest_state)}" %></h4>
          <p>回国时间：<%= trip.return_date %></p>
          <p>行程描述：<%= trip.description %></p>
          <%= link_to '查看', trip, class: "btn btn-primary", style: "width: 230px;" %>
        </div>
      </div>
    <% if i%4 == 3 || i == @trips.count-1 %>
      </div>
    <% end %>
    <% i = i + 1 %>
  <% end %>

<% else %>

  <p>还未创建行程</p>

<% end %>

app/views/trips/new.html.erb
      <h4>发布您的行程</h4>
      <div class="row">
        <div class="col-xs-4">
        </div>
        <div class="col-xs-8">
        	<%= render 'form' %>
        </div>
      </div>

app/views/trips/select_application.html.erb
      <h4>选择代购请求</h4>
      <div class="row">
        <div class="col-xs-4">
        </div>
        <div class="col-xs-8">
          <% if @trip.purchasings.count > 0 %>
          <%= form_tag("/trips/#{@trip.id}/update_application", :method => "post") do %>
            <% i = 0 %>
            <% @trip.purchasings.each do |purchasing| %>
            <% if i!=@trip.purchasings.count && i%3 == 0 %>
                <div class="row demo-tiles">
              <% end %>
                <div class="col-xs-4">
                  <div class="tile">
                    <%= image_tag purchasing.user.avatar_url(:medium) %>
                    <h4><%= purchasing.user.name %></h4>
                    <p><%= purchasing.item_name %></p>
                    <p><%= purchasing.item_type %></p>
                    <p>愿付酬金：<%= purchasing.remuneration %>人民币</p>
                    <p>时间：从<%= purchasing.arrival_time_start %></p>
                    <p>到<%= purchasing.arrival_time_end %></p>
                    <p>货物描述：<%= purchasing.item_desc %></p>
                    <label class="checkbox">
                      <%= check_box_tag 'checkbox[]', purchasing.id %>
                      选择TA
                    </label>
                  </div>
                </div>
              <% if i%3 == 2 || i == @trip.purchasings.count-1 %>
                </div>
              <% end %>
              <% i = i + 1 %>
            <% end %>
            <div class="form-group" style="margin-left: 30px;">
              <%=submit_tag( "提交" ,class: "btn btn-primary", style: "width: 150px;")%>
            </div>
          <% end %>
          <% else %>
            <p>暂时还没有代购请求，请您耐心等待</p>
          <% end %>
        </div>
      </div>

app/views/trips/show.html.erb
<script>
			jQuery(document).ready(function($){

				$('#etalage').etalage({
					thumb_image_width: 300,
					thumb_image_height: 300,
					source_image_width: 600,
					source_image_height: 600,
					show_hint: false
				});

			});

			$(function () {
      // Slideshow 1
      $("#slider2").responsiveSlides({
         auto: true,
		 nav: true,
		 speed: 500,
		 namespace: "callbacks",
      });
    });
		</script>


						



				<div class="slider2">
				<ul class="rslides rslider" id="slider2">		
					<% @trip.pictures.each do |picture| %>		  
				  	<li><%= image_tag picture.attachment.url(:large) %></li>
				  <% end %>
				</ul>
		   </div>

		   <ul id="etalage">
						  <% @trip.pictures.each do |picture| %>
							<li>
								<%= image_tag picture.attachment.url(:large), class: "etalage_thumb_image img-responsive"%>
								<%= image_tag picture.attachment.url(:large), class: "etalage_source_image img-responsive"%>
							</li>
							<% end %>
						</ul>


		<%=link_to "求帮忙", new_trip_product_path(@trip) %>