config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :trips do
    resources :products
    member do
      get 'select_application'
      post 'update_application'
      post 'commit_application'
    end
  end

  resources :products do
    resources :purchasings
  end

  get 'welcome/index'

  devise_for :users
  namespace :api do
    post 'users/sign_in' => 'sessions#create'
    post 'users/sign_up' => 'registrations#create'
  end

  root 'welcome#index'

  get '/edit_avatar' => 'user_manage#edit_avatar'
  patch '/update_avatar' => 'user_manage#update_avatar'

  get "/:member_id" => "user_manage#show", :as => "member"

end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :pictures, :cascade_callbacks => true
  accepts_nested_attributes_for :pictures
  has_many :purchasings, :dependent => :destroy
  accepts_nested_attributes_for :purchasings
  belongs_to :trip
  belongs_to :user

  field :expiration_date, type: Date #下单截止日期
  field :name, type: String #产品名称
  field :brand, type: String #品牌
  field :price, type: BigDecimal #预计单价
  field :color, type: String #颜色
  field :size, type: String #商品尺寸，规格及大小
  field :pur_num, type: BigDecimal, default: 0

  before_create do
    self.expiration_date = self.trip.expiration_date
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_trip

  respond_to :html

  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
    respond_with([@trip, @product])
  end

  def new
    @product = Product.new
    4.times { @product.pictures.build }
    @product.purchasings.build
    respond_with([@trip, @product])
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.trip = @trip
    @product.save
    respond_with([@trip, @product])
  end

  def update
    @product.update(product_params)
    respond_with([@trip, @product])
  end

  def destroy
    @product.destroy
    respond_with([@trip, @product])
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def product_params
      params.require(:product).permit(:name, :brand, :price, :color, :size, pictures_attributes: [:attachment], purchasings_attributes: [:expect_time_start, :expect_time_end, :remuneration, :memo, :quantity])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@trip, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :产品名称 %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="row">
    <%= f.label :品牌 %><br>
    <%= f.text_area :brand, class: "form-control", placeholder: "例如：Iphone" %>
  </div>
  <div class="row">
    <%= f.label :预计单价 %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="row">
    <%= f.label :颜色 %><br>
    <%= f.text_field :color, class: "form-control" %>
  </div>
  <div class="row">
    <%= f.label :商品尺寸，规格及大小 %><br>
    <%= f.text_field :size, class: "form-control" %>
  </div>
  <%= f.fields_for :pictures do |image| %>
    <% if image.object.new_record? %>
      <div class="row">
        <%= image.label :图片 %><br>
        <%= image.file_field :attachment, class: "form-control" %>
      </div>
    <% end %>
  <% end %>
  <br/>
  <%= f.fields_for :purchasings do |purchasing| %>
    <div class="row">
      <%= purchasing.label :期望到货时间 %><br>
      <%= purchasing.text_field :expect_time_start, class: "form-control" %>
    </div>
    <div class="row">
      <%= purchasing.label :期望到货时间 %><br>
      <%= purchasing.text_field :expect_time_end, class: "form-control" %>
    </div>
    <div class="row">
      <%= purchasing.label :酬金 %><br>
      <%= purchasing.text_field :remuneration, class: "form-control" %>
    </div>
    <div class="row">
      <%= purchasing.label :备注 %><br>
      <%= purchasing.text_field :memo, class: "form-control" %>
    </div>
    <div class="row">
      <%= purchasing.label :数量 %><br>
      <%= purchasing.text_field :quantity, class: "form-control" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
  /* <![CDATA[ */
  jQuery(function(){
    jQuery("#product_name").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请选择国家"
    });
    jQuery("#product_brand").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请填写回国日期"
    });
    jQuery("#product_price").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
    jQuery("#product_size").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
    jQuery("#product_pictures_attributes_0_attachment").validate({
      expression: "if (VAL) return true; else return false;",
      message: "请输入代购商品单价"
    });
  });
  /* ]]> */
</script>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_path(@trip) %>

app/views/products/show.html.erb
<script>
			jQuery(document).ready(function($){

				$('#etalage').etalage({
					thumb_image_width: 300,
					thumb_image_height: 300,
					source_image_width: 600,
					source_image_height: 600,
					show_hint: false
				});

			});

		</script>


						

		   <ul id="etalage">
						  <% @product.pictures.each do |picture| %>
							<li>
								<%= image_tag picture.attachment.url(:large), class: "etalage_thumb_image img-responsive"%>
								<%= image_tag picture.attachment.url(:large), class: "etalage_source_image img-responsive"%>
							</li>
							<% end %>
						</ul>


		<%=link_to "求帮忙", new_product_purchasing_path(@product) %>